name: "CD"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-docker-images: 'true'
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: suyashtnt
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: cachix use helix
    - run: cachix use niri
    - run: cachix use fortuneteller2k
    - run: cachix use nix-community
    - run: nix build -L
    - name: Deploy
      if: github.ref == 'refs/heads/main'
      env:
        CACHIX_ACTIVATE_TOKEN: "${{ secrets.CACHIX_ACTIVATE_TOKEN }}"
      run: |
        cachix push suyashtnt ./result
        cachix deploy activate ./result
